import { PerspectiveCamera } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import LandingLayout from "components/layout/LandingLayout";
import Scene from "components/threejs/scene";
import Head from "next/head";
import { Suspense } from "react";
import { useTranslation } from "react-i18next";
import {BsFillArrowRightCircleFill} from 'react-icons/bs'
import styles from 'styles/home.module.sass'
import localStyles from './transaction.module.sass'
export default function Transaction() {
    const {t} = useTranslation()
    return <LandingLayout
        logo={
            <h1 className={styles.logo}><span>x</span> project</h1>
        }
    >
        <Head>
            <title>X Project | Transaction</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
            <div className={styles.fixedbg}></div>
            <div className={styles.animatedbg}>

                <Canvas style={{ height: '100vh', width: '100vw', zIndex: -1 }}
                    dpr={[1, 2]} >
                    <Suspense fallback={null}>
                        <PerspectiveCamera makeDefault position={[0, 0, 10]} fov={75} />
                        <ambientLight intensity={1} position={[10, 10, 0]} />
                        <Scene />
                    </Suspense>
                </Canvas>
            </div>
            <div className={localStyles.content}>
                <h2>{t('user')}: <span>Juan Hebert Chable</span></h2>
                <div className={localStyles.preview}>
                    <div className={localStyles.box}>
                        <div className={localStyles.title}>{t('balance-due')}</div>
                        <div className={localStyles.text}>1.255 BTC</div>
                    </div>
                    <div className={localStyles.convert}>
                        <div className={localStyles.icon}>
                            <BsFillArrowRightCircleFill/>
                        </div>
                    </div>
                    <div className={localStyles.box}>
                        <div className={localStyles.title}>{t('land-to-receive')}</div>
                        <div className={localStyles.text}>6</div>
                    </div>
                </div>
                <form action='/'>
                <input type="submit" value={t('confirm-transaction')}/>
                </form>
            </div>
        </div>
    </LandingLayout>
}