import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/home.module.sass'
import { BsFillPlayFill, BsFillPlayCircleFill } from 'react-icons/bs'
import { IoIosWallet, IoWallet } from 'react-icons/io'
import { motion } from 'framer-motion'
import { zoom, side } from 'effects/effects'
import { Canvas } from '@react-three/fiber'
import { Suspense } from 'react'

import { PerspectiveCamera } from '@react-three/drei'
import Wave from 'components/threejs/wave'
import { Bloom, EffectComposer } from '@react-three/postprocessing'
import Scene from 'components/threejs/scene'
import LandingLayout from 'components/layout/LandingLayout'
import { useTranslation } from 'react-i18next'
export default function Home() {
  const {t} = useTranslation()
  return (
    <LandingLayout
      logo={
        <h1><span>x</span> project</h1>
      }
      >
      <div>
        <Head>
          <title>X Project</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.fixedbg}></div>
        <div className={styles.animatedbg}>
          <Canvas style={{ height: '100vh', width: '100vw', zIndex: -1 }}
            dpr={[1, 2]} >
            <Suspense fallback={null}>
              <PerspectiveCamera makeDefault position={[0, 0, 10]} fov={75} />
              <ambientLight intensity={1} position={[10, 10, 0]} />
              <Scene />
            </Suspense>
          </Canvas>

        </div>

        <main className={styles.home}>
          <section className={`${styles.fixedSize} ${styles.first}`}>
            <div className={styles.centeredContent}>
              <motion.h1
                variants={side}
                initial="hidden"
                whileInView="visible"
                className={styles.title}><span>x</span> project</motion.h1>
              <div className={styles.text}>
                <motion.p
                  variants={zoom}
                  initial="zoomOut"
                  whileInView="visible"
                > 
                {t('welcome')}
                </motion.p>
              </div>
              <div className={styles.borderedContainer}>
                <div className={styles.bg}>
                  <Image alt="video" src={'/assets/images/video_banner.png'} style={{ "objectFit": "cover" }} fill={true} />
                </div>
                <div className={styles.play}>
                  <BsFillPlayFill />
                </div>
              </div>
            </div>
          </section>
          <section className={styles.adaptativeSize}>
            <div className={styles.adaptativeContent}>
              <div className={styles.imageWithText}>
                <motion.div className={styles.image}
                  variants={zoom}
                  initial="zoomOut"
                  whileInView="visible"
                >
                  <div className={styles.borderedContainer}>
                    <div className={styles.bg}>
                      <Image src="/assets/images/what_is.png" alt="what is: image" style={{ "objectFit": "cover" }} fill="true" />
                    </div>
                  </div>
                </motion.div>
                <motion.div className={styles.text}
                  variants={zoom}
                  initial="zoomOut"
                  whileInView="visible"
                >
                  <h1>
                    ¿Qué es el <span>Metaverso</span>?
                  </h1>
                  <p>
                    El Metaverso es un concepto de un universo 3D persistente en linea que combina múltiples espacios virtuales diferentes. Puedes pensar esto como versión futura del internet. El Metaverso permitirá a los usuarios trabajar, reunirse, jugar y socializar juntos en estos
                    espacios 3D
                  </p><p>
                    El mercado económico para el Metaverso crecerá para el 2030 de manera drástica. En el comercio electrónico se calcula que el impacto se situaría entre los 2 y 2,6 billones de dólares, mientras que en la educación podría generar hasta 270.000 millones de dólares y, en
                    el mercado de videojuegos, su impacto podría ser de hasta 125.000 millones de dólares.
                  </p>
                </motion.div>
              </div>
            </div>
          </section>

          <section className={styles.fixedSize}>
            <div className={styles.centeredContent}
            >
              <motion.div
                 variants={zoom}
                 initial="zoomOut"
                 whileInView="visible"
                className={styles.imageWithText}>

                <div className={styles.text}>
                  <h1>
                    ¿Qué es <span>Landian</span>?
                  </h1>
                  <p>
                    El metaverso mas hiperealista de la historia conectado
                    Con blockchain y amigable con la web 3.0.
                  </p><p>
                    LANDIAN rompió récord de ventas el día
                    de su lanzamiento, vendiendo en un solo día
                    más de 90 mil NFT.
                  </p>
                </div>
                <div className={styles.image}>
                  <div className={styles.borderedContainer}>
                    <div className={styles.bg}>
                      <Image src="/assets/images/landian.png" alt="landian" style={{ "objectFit": "cover" }} fill="true" />
                    </div>
                  </div>
                </div>
              </motion.div>
            </div>
          </section>

          <section className={`${styles.fixedSize} ${styles.third}`}>
            <div className={styles.centeredContent}>
              <h1>Tutorial</h1>
              <div className={styles.steps}>
                <div className={styles.step1}>
                  <h2>
                    <span>1</span>
                    {t('first-step-title')}
                  </h2>
                  <div className={styles.icon}>
                    <BsFillPlayCircleFill />
                  </div>
                  <div className={styles.desc}>{t('first-step-desc')}</div>
                </div>
                <div className={styles.step2}>
                  <h2>
                    <span>2</span>
                    {t('second-step-title')}
                  </h2>
                  <div className={styles.icon}>
                    <IoIosWallet />
                  </div>
                  <div className={styles.desc}>{t('second-step-desc')}</div>
                </div>
                <div className={styles.step3}>
                  <h2>
                    <span>3</span>
                    {t('third-step-title')}
                  </h2>
                  <div className={styles.icon}>
                    <BsFillPlayCircleFill />
                  </div>
                  <div className={styles.desc}>{t('third-step-desc')}</div>
                </div>
              </div>
            </div>
          </section>
        </main>
      </div>
    </LandingLayout>

  )
}
